urls.py
from django.urls import path

from . import views

app_name = 'vote'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', views.AdminView.as_view(), name='admin'),
    path('season_update/', views.season_update_view, name='season_update'),
    path('topic_create/', views.TopicCreateView.as_view(), name='topic_create'),
    path('topic/<slug:slug>/', views.TopicDetailView.as_view(), name='topic_detail'),
    path('topic/<slug:slug>/vote/', views.topic_vote_view, name='topic_vote'),
    path('topic/<slug:slug>/edit/', views.TopicUpdateView.as_view(), name='topic_edit'),
    path('topic/<slug:slug>/delete/', views.topic_delete_view, name='topic_delete'),
    path('topic/<slug:slug>/approve/', views.topic_approve_view, name='topic_approve'),
    path('topic/<slug:slug>/toggle_comment/', views.topic_toggle_comment_view, name='topic_toggle_comment'),
    path('add_comment/', views.CommentCreateView.as_view(), name='comment'),
    path('group_create/', views.GroupCreateView.as_view(), name='group_create'),
    path('group/<int:pk>/', views.GroupView.as_view(), name='group'),
    path('group/<int:pk>/edit/', views.GroupEditView.as_view(), name='group_edit'),
    path('group/<int:pk>/delete/', views.group_delete_view, name='group_delete'),
    path('user_history/', views.UserHistoryView.as_view(), name='user_history'),
    path('approved_topics/', views.ApprovedTopicsView.as_view(), name='approved_topics'),
    path('upload/<file_type>/', views.upload_view, name='upload'),
]

models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.translation import gettext as _

from .abstract_models import AbstractVote, SingletonModel, slug_generator


User = settings.AUTH_USER_MODEL


class Settings(SingletonModel):
    can_vote = models.BooleanField(_('Can Users Vote'), default=True)

    class Meta:
        verbose_name = _('Settings')
        verbose_name_plural = _('Settings')

    def __str__(self):
        return _('Settings')


class Group(models.Model):
    title = models.CharField(_('Group Name'), max_length=32)
    desc = models.CharField(_('Group Description'), max_length=1024, blank=True)

    class Meta:
        verbose_name = _('Group')
        verbose_name_plural = _('Groups')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('vote:group', args=[self.pk])


class Topic(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE,
                              related_name='topic', verbose_name=_('Group'))
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), max_length=255, blank=True, null=True)
    desc = models.CharField(_('Topic Description'), max_length=512)
    date = models.DateTimeField(_('Date'), auto_now_add=True, blank=True, null=True)
    body = models.TextField(_('Topic Body'), blank=True)
    approved = models.BooleanField(_('Is Approved'), default=False)
    can_comment = models.BooleanField(_('Can Comment'), default=True)
    vote_count = models.PositiveSmallIntegerField(_('Vote Count'), default=0)

    class Meta:
        verbose_name = _('Topic')
        verbose_name_plural = _('Topics')
        ordering = ['-date']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slug_generator(self.__class__, self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('vote:topic_detail', args=[self.slug])


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,
                              related_name='comment', verbose_name=_('Topic'))
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='comment', verbose_name=_('User'))
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='comment', verbose_name=_('Parent'))
    body = models.TextField(_('Comment Body'))
    date = models.DateTimeField(_('Date'), auto_now_add=True, blank=True, null=True)
    vote_count = models.PositiveSmallIntegerField(_('Vote Count'), default=0)

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return self.topic.title

    def get_absolute_url(self):
        return self.topic.get_absolute_url()


class File(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True,
                              related_name='file', verbose_name=_('Topic'))
    title = models.CharField(_('File Title'), max_length=64, null=True, blank=True)
    file = models.FileField(_('File'), upload_to='files/')
    random_key = models.CharField(_('Random Key'), max_length=16, blank=True, null=True)

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')

    def __str__(self):
        return self.title or 'Null'


class Image(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True,
                              related_name='image', verbose_name=_('Topic'))
    title = models.CharField(_('Image Title'), max_length=64, null=True, blank=True)
    image = models.ImageField(_('Image'), upload_to='images/')
    random_key = models.CharField(_('Random Key'), max_length=16, blank=True, null=True)

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')

    def __str__(self):
        return self.title or 'Null'


class TopicVote(AbstractVote):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,
                              related_name='vote', verbose_name=_('Topic'))

    class Meta:
        verbose_name = _('Topic Vote')
        verbose_name_plural = _('Topic Votes')
        unique_together = [['topic', 'user']]

    def __str__(self):
        return f'{self.topic} - {self.user}'


class CommentVote(AbstractVote):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE,
                                related_name='vote', verbose_name=_('Comment'))

    class Meta:
        verbose_name = _('Comment Vote')
        verbose_name_plural = _('Comment Votes')
        unique_together = [['comment', 'user']]

    def __str__(self):
        return f'{self.comment} - {self.user}'

forms.py
from django import forms

from .models import Topic, File, Image


class FileForm(forms.ModelForm):
    title = forms.CharField(required=True)

    class Meta:
        model = File
        fields = ['title']

    def clean_id(self):
        id = self.cleaned_data['id']
        return id


class ImageForm(forms.ModelForm):
    title = forms.CharField(required=True)

    class Meta:
        model = Image
        fields = ['title']

    def clean_id(self):
        id = self.cleaned_data['id']
        return id


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['group', 'title', 'desc', 'body']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].widget.attrs.update({'class': 'custom-select mr-sm-2'})


ImageFormSet = forms.inlineformset_factory(Topic, Image, form=ImageForm, extra=1)
FileFormSet = forms.inlineformset_factory(Topic, File, form=FileForm, extra=1)

templates/vote/admin.html
{% extends 'vote/base.html' %}

{% load i18n %}
{% load vote_tags %}

{% block title %} | {% trans 'Admin' %}{% endblock title %}

{% block body %}
<div id="group_list" class="mt-4">
  {% csrf_token %}
</div>
{% endblock body %}

{% block sidebar_extra %}
  <div class="my-4 p-3 bg-white rounded shadow-sm" >
    <h5>{% trans 'Admin' %}</h5>
    <hr>
    <div id="control_buttons"></div>
  </div>
{% endblock sidebar_extra %}

{% block extrajs %}
<script>
  webix.attachEvent("onBeforeAjax", function(mode, url, data, xhr, headers){
		var key = document.querySelector("[name=csrfmiddlewaretoken]").value;
		headers["X-CSRFToken"] = key;
	});
  var grid = {
    view:"datatable", id:"datatable1",
    columns:[
      { id:"title", editor:"text", header:"{% trans 'Title' %}", width:170},
      { id:"desc", editor:"popup", header:"{% trans 'Description' %}", width:270},
      {% if request.user|check_role:'can_delete_group' %}
        { id:"delete", header:"{% trans 'Delete' %}", width:60,
          template:function(obj){
            return "<div class='webix_el_button'><button class='webixtype_base btn btn-danger btn-sm text-center'>Del</button></div>";
          }
        }
      {% endif %}
    ],
    
    onClick:{
      webixtype_base:function(ev, id, html){
        webix.confirm({
            title: "Delete",
            text: "Are you sure you want to delete the selected item?",
            callback: function(result) { 
                if (result) {
                  $$("datatable1").remove(id);
                } 
            }
        });
      }
    },

    select:true,
    autoheight:true,
    autowidth:true,
    data: [
      {% for group in groups %}
        { id:{{ group.pk }}, title:"{{ group.title }}", desc:"{{ group.desc }}" },
      {% endfor %}
    ],
    save: {
      'update':function(view, params, dp){
        webix.ajax().post("/group/"+dp.id+"/edit/",{ title:dp.title, desc:dp.desc });
      },
      'insert':function(view, params, dp){
        webix.ajax().post("{% url 'vote:group_create' %}",{ title:dp.title, desc:dp.desc });
      },
      'delete':function(view, params, dp){
        webix.ajax().post("/group/"+dp.id+"/delete/");
      }
    },
    on: {
      onSelectChange: function(){
       var group = this.getSelectedItem();
       $$('topic').filter(function(obj){
        return obj.group == group.title;
      });
     }
    }
  };

var form = {
  view:"form", id:"form1", scroll:false,
  elements:[
    { view:"text", name:"title", label:"{% trans 'Title' %}" },
    { view:"textarea", name:"desc", label:"{% trans 'Desc' %}" },
    
    {% if request.user|check_role:"can_edit_group" or request.user|check_role:"can_create_group" %}
      { view:"button", value:"{% trans 'Save' %}", click:'$$("form1").save()' },
    {% endif %}

    {% if request.user|check_role:"can_create_group" %}
      { view:"button", value:"{% trans 'Create New' %}", click:'groupButtonClick' },
    {% endif %}
  ],
};

  var topic = {
    view:"datatable",
    id:"topic",
    xCount: 1,
    template:"#title#",
    height:400,
    type: {
      width:"auto",
      height:"auto",
    },
    columns:[
      { id:"vote", header:"{% trans 'Votes' %}", width:50 },
      { id:"title", editor:"text", header:"{% trans 'Title' %}", width:170},
      { id:"desc", editor:"text", header:"{% trans 'Description' %}", fillspace:true},
      { id:"group", editor:"text", header:"{% trans 'Group' %}", autosize:true},
    ],
    data: [
      {% for topic in topics %}
      {
        "title":"{{ topic.title }}", 
        "vote":{{ topic.vote_count }},
        "group":'{{ topic.group }}',
        "desc":"{{ topic.desc|escapejs }}",
      },
      {% endfor %}
    ]
  };

webix.ready(function(){
  webix.ui({
    container:'group_list',
    rows:[
      {type:"wide", height:27, cols:[ { template:"<b>Group List</b>", width:500 }, { template:"<b>Group Form</b>" } ]},
      {type:"wide", cols:[ grid, form ]},
      { template:"<b>Topic List Filtered By Group</b>", height:27 },
      topic,
    ]
  });
  $$('form1').bind('datatable1')
});

function groupButtonClick(){
  $$('datatable1').unselectAll();
  $$('form1').focus();
};

var season_switch = {
  id:"season_switch",
  view: "switch",
  label: "{% trans 'Voting' %}:",
  onLabel: "{% trans 'Active' %}",
  offLabel:"{% trans 'Inactive' %}",
  {% get_season_active as season_active %}
  {% if season_active %}
    value: 1,
  {% else %}
    value: 0,
  {% endif %}
  {% if not request.user|check_role:'can_control_season' %}
    disabled: true,
  {% endif %}
  click:function(){
    webix.confirm({
      title: "Approve",
      text: "{% trans 'Are you sure you want to change voting settings?' %}",
      callback: function(result) { 
        if (result) {
          webix.ajax().post("{% url 'vote:season_update' %}");
          webix.message("{% trans 'Voting settings changed successfuly' %}");
        } else {
          $$('season_switch').toggle()  
        } 
      }
    });
  }
};

var topic_create_btn = {
  view:"button",
  id:"topic_create_btn", 
  value:"{% trans 'Create a Topic' %}", 
  css:"webix_primary", 
  click:function(){
    window.location = "{% url 'vote:topic_create' %}";
  }
};

var group_create_btn = {
  view:"button",
  id:"group_create_btn", 
  value:"{% trans 'Create a Group' %}", 
  css:"webix_primary", 
  click:groupButtonClick,
};

webix.ui({
  container:"control_buttons",
  rows:[
    {% if request.user|check_role:"can_control_season" %}
      season_switch,
    {% endif %}
    {% if request.user|check_role:"can_create_topic" %}
      topic_create_btn,
    {% endif %}
    {% if request.user|check_role:"can_create_group" %}
      group_create_btn,
    {% endif %}
  ]
});
</script>
{% endblock %}

templates/vote/topic.html
{% extends 'vote/base.html' %}

{% load i18n %}
{% load static %}
{% load vote_tags %}

{% block title %}
| {% trans 'Topic' %}: {{ topic.title }}
{% endblock title %}

{% block body %}
  <div class="media text-muted pt-3">
    {% include 'vote/partial/vote_button.html' %}
    <div class="media-body ml-3 pb-3 mb-0 lh-125">
      <h3 class="d-block text-gray-dark">{{ topic.title }}</h3>
      <p>
      {{ topic.body|safe }}
      </p>
      {% for i in topic.image.all %}
        <a href="{{ i.image.url }}" target="_Blank">
          <img class="img-fluid" src="{{ i.image.url }}" style="height:150px;width:150px;object-fit:cover" >
        </a>
      {% endfor %}
      {% if object.file.all %}
      <h5 class="mt-2">{% trans 'Files' %}</h5>
        <ul class="list-inline">
          {% for file in object.file.all %}
          <li>
            <a href="{{ file.file.url }}">{{ file.title }}</a>
          </li>
          {% endfor %}
        </ul>
      {% endif %}
      <hr>
      <div id="comment_list" style="height:40vh">
          {% csrf_token %}
      </div>
      {% if not request.user|check_role:"can_comment" or not topic.can_comment %}
      {% else %}
        <form method="post" action="{% url 'vote:comment' %}">
          {% csrf_token %}
          <input type="hidden" id="id_topic" name="topic" value="{{ topic.pk }}">
          <input type="hidden" id="id_user" name="user" value="{{ request.user.pk }}">
          <input type="hidden" id="id_parent" name="parent" value="">
          <div class="form-group">
            <textarea class="form-control" id="id_body" name="body" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-primary mb-2">{% trans 'Send' %}</button>
        </form>
        <script src="{% static 'vote/jquery.formset.js' %}"></script>
        <script src='https://cdn.tiny.cloud/1/{% get_tinymce_key %}/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script>
        <script>
        tinymce.init({
          selector: 'textarea',
          branding: false,
          menubar: false,
        });
        </script>
      {% endif %}

    </div>
  </div>
{% endblock body %}

{% block sidebar_extra %}
{% if request.user|is_admin %}
  <div class="my-4 p-3 bg-white rounded shadow-sm">
    <h5>{% trans 'Topic Control' %}</h5>
    <hr>
    <div id="control_buttons">
    </div>
  </div>
{% endif %}
{% endblock sidebar_extra %}

{% block extrajs %}
<script>
  webix.attachEvent("onBeforeAjax", function(mode, url, data, xhr, headers){
		var key = document.querySelector("[name=csrfmiddlewaretoken]").value;
		headers["X-CSRFToken"] = key;
	});
  webix.ui({   
    view:"comments",
    id:"comments",
    container:"comment_list",
    height:"400",
    currentUser:{{ request.user.id }},
    data:[
      {% for comment in topic.comment.all %}
        {
          id:{{ comment.id }}, user_id:{{ comment.user.id }}, date:"{{ comment.date|date:'Y-m-j G:i' }}",
            text:"{{ comment.body|escapejs }}"
        },
      {% endfor %}
    ],
    users:[
      {% for user in users %}
      { id:{{ user.id }}, value:"{{ user.get_full_name }}", image: "{{ user|get_avatar }}" },
      {% endfor %}
    ],
    save:function(view, params, dp){
      webix.ajax().post("{% url 'vote:comment' %}",{ body:dp.text, user:dp.user_id, topic:{{ topic.pk }} });
    },
    readonly:true,
  });
  
  var edit_btn = {
    view:"button",
    id:"edit_btn", 
    value:"{% trans 'Edit This Topic' %}", 
    css:"webix_primary", 
    click:function(){
      window.location = "{% url 'vote:topic_edit' topic.slug %}";
    }
  };

  var delete_btn = {
    view:"button",
    id:"delete_btn", 
    value:"{% trans 'Delete This Topic' %}", 
    css:"webix_danger", 
    click:function(){
      webix.confirm({
        title: "Delete",
        text: "{% trans 'Are you sure you want to delete this topic?' %}",
        callback: function(result) { 
          if (result) {
            window.location = "{% url 'vote:topic_delete' topic.slug %}";
          } 
        }
      });
    }
  };

  var approve_btn = {
    view: "switch",
    id:"approve_btn",
    label: "{% trans 'Is Approved?' %}:",
    labelWidth:165,
    {% if topic.approved %}value: 1,{% else %}value: 0,{% endif %}
    {% if not request.user|check_role:'can_approve_topic' %}
      disabled: true,
    {% endif %}
    click:function(){
      webix.confirm({
        title: "Approve",
        text: "{% trans 'Are you sure you want to approve/disapprove this topic?' %}",
        callback: function(result) { 
          if (result) {
            webix.ajax().post("{% url 'vote:topic_approve' topic.slug %}");
            webix.message("{% trans 'Approval status changed successfuly' %}");
          } else {
            $$('approve_btn').toggle()  
          } 
        }
      });
    }
  };

  var toggle_comment_btn = {
    view: "switch",
    id:"toggle_comment_btn",
    label: "{% trans 'Can Comment?' %}:",
    labelWidth:165,
    {% if topic.can_comment %}value: 1,{% else %}value: 0,{% endif %}
    {% if not request.user|check_role:'can_approve_topic' %}
      disabled: true,
    {% endif %}
    click:function(){
      webix.confirm({
        title: "Approve",
        text: "{% trans 'Are you sure you want to activate/inactivate comments for this topic?' %}",
        callback: function(result) { 
          if (result) {
            webix.ajax().post("{% url 'vote:topic_toggle_comment' topic.slug %}");
            webix.message("{% trans 'Comment status changed successfuly' %}");
            location.reload(); 
          } else {
            $$('toggle_comment_btn').toggle()
          }
        }
      });
    }
  };
  
  webix.ui({
    container:"control_buttons",
    rows:[
      {% if request.user|check_role:"can_approve_topic" %}
        approve_btn,
        toggle_comment_btn,
      {% endif %}
      {% if request.user|check_role:"can_edit_topic" %}
        edit_btn,
      {% endif %}
      {% if request.user|check_role:"can_delete_topic" %}
        delete_btn,
      {% endif %}
    ]
  });
</script>
{% endblock extrajs %}

templates/vote/topic_form.html
{% extends 'vote/base.html' %}

{% load static %}
{% load vote_tags %}
{% load i18n %}

{% block title %} | {% if topic %}{% trans 'Edit Topic' %}{% else %}{% trans 'Create Topic' %}{% endif %}{% endblock title %}

{% block body %}
<div class="container mt-4">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="row">
      {{ form.title.errors }}
      <div class="form-group row col-md-10">
        <label class="col-sm-2 col-form-label" for="id_title">{% trans 'Title' %}</label>
        <div class="col-sm-10" style="padding-left: 2.35em;">
          <input class="form-control" type="text" class="form-control" id="id_title" name="title" {% if form.title.value %}value="{{ form.title.value }}"{% endif %}>
        </div>
      </div>

      <div class="form-group row col-md-2 pr-0">
          <button type="submit" class="btn btn-primary btn-block">{% trans 'Send' %}</button>
      </div>

      {{ form.group.errors }}
      <div class="form-group row col-md-12">
        <label class="col-sm-2 col-form-label" for="id_group">{% trans 'Group' %}</label>
        <div class="col-sm-10">
          {{ form.group }}
        </div>
      </div>
    
      {{ form.desc.errors }}
      <div class="form-group row col-md-12">
        <label class="col-sm-2 col-form-label" for="id_desc">{% trans 'Topic Description' %}</label>
        <div class="col-sm-10">
          <textarea class="form-control" class="form-control" id="id_desc" maxlength="512" name="desc" rows="1">{% if form.desc.value %}{{ form.desc.value }}{% endif %}</textarea>
        </div>
      </div>

      {{ form.body.errors }}
      <div class="form-group row col-md-12">
        <label class="col-sm-2 col-form-label" for="id_body">{% trans 'Topic Body' %}</label>
        <div class="col-sm-10">
          <textarea class="form-control" class="form-control" id="id_body" name="body" rows="16">{% if form.body.value %}{{ form.body.value }}{% endif %}</textarea>
        </div>
      </div>
      <fieldset class="col-md-6">
        {{ file_formset.management_form }}
        {{ file_formset.non_form_errors }}
        <div id="file_uploader_container" style="width: 100%; height: 200px"></div>
      </fieldset>
      <fieldset class="col-md-6">
        {{ image_formset.management_form }}
        {{ image_formset.non_form_errors }}
        <div id="image_uploader_container" style="width: 100%; height: 200px"></div>
      </fieldset>
    </div>
  </form>
</div>
{% endblock body %}

{% block extrajs %}
<script src="{% static 'vote/jquery.formset.js' %}"></script>
<script src='https://cdn.tiny.cloud/1/{% get_tinymce_key %}/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script>
<script>
tinymce.init({
  selector: '#id_body',
  branding: false
});
</script>
<script>
  webix.attachEvent("onBeforeAjax", function(mode, url, data, xhr, headers){
		var key = document.querySelector("[name=csrfmiddlewaretoken]").value;
		headers["X-CSRFToken"] = key;
	});

webix.ready(function() {
  webix.ui({
    container:"file_uploader_container",
    view:"form", rows: [
      { 
        view: "uploader", value: 'Upload file', 
        id:"files", name:"files",
        link:"filelist",  upload:"{% url 'vote:upload' 'file' %}" 
      },
      {
        view:"list",  id:"filelist", type:"uploader",
        autoheight:true, borderless:true,
        type:{
          height:70
        },
        template:function (obj) {
          if (typeof obj.fs_id !== 'undefined' || obj.fs_id === null) {
            var fs_id = obj.fs_id;
          } else {
            var fs_id = $$("filelist").getVisibleCount() - 1;
          }
        return '<input type="hidden" name="file-' + fs_id + '-id" value="' + obj.pk + '" id="id_file-' + fs_id + '-id">' +
          '<input type="text" style="width:94%; height:30px" id="id_file-' + fs_id + '-title" name="file-' + fs_id + '-title" placeholder="{% trans 'Please Enter a Title' %}" value="' + obj.title + '">' +
            '<input type="hidden" name="file-' + fs_id + '-topic" {% if topic.pk %}value="{{ topic.pk }}" {% endif %}id="id_file-' + fs_id + '-topic">' + 
          '<div class="remove_file" style="display:inline"><span style="color:#AAA;float: right;" class="cancel_icon"></span></div>' +
          '<p><small>' + obj.name + '</small></p>'
        }
      },
    ]
  });
  $$("files").files.parse([
    {% for file in topic.file.all %}
    { fs_id: '{{ forloop.counter0 }}', pk: '{{ file.pk }}', title: '{% if file.title %}{{ file.title }}{% endif %}', name: '{{ file.file.name}}' },
    {% endfor %}
  ]);

  webix.ui({
    container:"image_uploader_container",
    view:"form", rows: [
      { 
        view: "uploader", value: 'Upload image', 
        id:"images", name:"images",
        link:"imagelist",  upload:"{% url 'vote:upload' 'image' %}" 
      },
      {
        view:"list",  id:"imagelist", type:"uploader",
        autoheight:true, borderless:true,
        type:{
          height:70
        },
        template:function (obj) {
          if (typeof obj.fs_id !== 'undefined' || obj.fs_id === null) {
            var fs_id = obj.fs_id;
          } else {
            var fs_id = $$("imagelist").getVisibleCount() - 1;
          }
        return '<input type="hidden" name="image-' + fs_id + '-id" value="' + obj.pk + '" id="id_image-' + fs_id + '-id">' +
          '<input type="text" style="width:94%; height:30px" id="id_image-' + fs_id + '-title" name="image-' + fs_id + '-title" placeholder="{% trans 'Please Enter a Title' %}" value="' + obj.title + '">' +
            '<input type="hidden" name="image-' + fs_id + '-topic" {% if topic.pk %}value="{{ topic.pk }}" {% endif %}id="id_image-' + fs_id + '-topic">' + 
          '<div class="remove_file" style="display:inline"><span style="color:#AAA;float: right;" class="cancel_icon"></span></div>' +
          '<p><small>' + obj.name + '</small></p>'
        }
      },
    ]
  });
  $$("images").files.parse([
    {% for image in topic.image.all %}
      { fs_id: '{{ forloop.counter0 }}', pk: '{{ image.pk }}', title: '{% if image.title %}{{ image.title }}{% endif %}', name: '{{ image.image.name}}' },
    {% endfor %}
  ]);
});
</script>
<style>
.del-btn {
  position: absolute;
  right: 1rem;
}
.add-btn {
  float: inline-end;
}
</style>
<textarea id="file_template_container" hidden="">
  <input type="hidden" name="file-#id#-id" value="#id#" id="id_file-#id#-id">
  <input type="text" style="width:94%; height:30px" id="id_file-#id#-title" name="file-#id#-title" placeholder="{% trans 'Please Enter a Title' %}" value="#title#">
  <div class='remove_file' style="display:inline"><span style='color:#AAA' class='cancel_icon'></span></div>
  <p><small>#name#</small></p>
  <input type="file" hidden="" id="id_file-#id#-file" name="file-#id#-file">
</textarea>
<textarea id="image_template_container" hidden="">
  <input type="hidden" name="image-#id#-id" value="#pk#" id="id_image-#id#-id">
  <input type="text" style="width:94%; height:30px" id="id_image-#id#-title" name="image-#id#-title" placeholder="{% trans 'Please Enter a Title' %}" value="#title#">
  <div class='remove_file' style="display:inline"><span style='color:#AAA' class='cancel_icon'></span></div>
  <p><small>#name#</small></p>
  <input type="file" hidden="" id="id_image-#id#-image" name="image-#id#-image">
</textarea>
{% endblock extrajs %}