urls.py
from django.urls import path

from . import views

app_name = 'vote'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', views.AdminView.as_view(), name='admin'),
    path('season_update/', views.season_update_view, name='season_update'),
    path('topic_create/', views.TopicCreateView.as_view(), name='topic_create'),
    path('topic/<slug:slug>/', views.TopicDetailView.as_view(), name='topic_detail'),
    path('topic/<slug:slug>/vote/', views.topic_vote_view, name='topic_vote'),
    path('topic/<slug:slug>/edit/', views.TopicUpdateView.as_view(), name='topic_edit'),
    path('topic/<slug:slug>/delete/', views.topic_delete_view, name='topic_delete'),
    path('topic/<slug:slug>/approve/', views.topic_approve_view, name='topic_approve'),
    path('topic/<slug:slug>/toggle_comment/', views.topic_toggle_comment_view, name='topic_toggle_comment'),
    path('add_comment/', views.CommentCreateView.as_view(), name='comment'),
    path('group_create/', views.GroupCreateView.as_view(), name='group_create'),
    path('group/<int:pk>/', views.GroupView.as_view(), name='group'),
    path('group/<int:pk>/edit/', views.GroupEditView.as_view(), name='group_edit'),
    path('group/<int:pk>/delete/', views.group_delete_view, name='group_delete'),
    path('user_history/', views.UserHistoryView.as_view(), name='user_history'),
    path('approved_topics/', views.ApprovedTopicsView.as_view(), name='approved_topics'),
    path('upload/<file_type>/', views.upload_view, name='upload'),
]

models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.translation import gettext as _

from .abstract_models import AbstractVote, SingletonModel, slug_generator


User = settings.AUTH_USER_MODEL


class Settings(SingletonModel):
    can_vote = models.BooleanField(_('Can Users Vote'), default=True)

    class Meta:
        verbose_name = _('Settings')
        verbose_name_plural = _('Settings')

    def __str__(self):
        return _('Settings')


class Group(models.Model):
    title = models.CharField(_('Group Name'), max_length=32)
    desc = models.CharField(_('Group Description'), max_length=1024, blank=True)

    class Meta:
        verbose_name = _('Group')
        verbose_name_plural = _('Groups')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('vote:group', args=[self.pk])


class Topic(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE,
                              related_name='topic', verbose_name=_('Group'))
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), max_length=255, blank=True, null=True)
    desc = models.CharField(_('Topic Description'), max_length=512)
    date = models.DateTimeField(_('Date'), auto_now_add=True, blank=True, null=True)
    body = models.TextField(_('Topic Body'), blank=True)
    approved = models.BooleanField(_('Is Approved'), default=False)
    can_comment = models.BooleanField(_('Can Comment'), default=True)
    vote_count = models.PositiveSmallIntegerField(_('Vote Count'), default=0)

    class Meta:
        verbose_name = _('Topic')
        verbose_name_plural = _('Topics')
        ordering = ['-date']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slug_generator(self.__class__, self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('vote:topic_detail', args=[self.slug])


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,
                              related_name='comment', verbose_name=_('Topic'))
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='comment', verbose_name=_('User'))
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='comment', verbose_name=_('Parent'))
    body = models.TextField(_('Comment Body'))
    date = models.DateTimeField(_('Date'), auto_now_add=True, blank=True, null=True)
    vote_count = models.PositiveSmallIntegerField(_('Vote Count'), default=0)

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return self.topic.title

    def get_absolute_url(self):
        return self.topic.get_absolute_url()


class File(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True,
                              related_name='file', verbose_name=_('Topic'))
    title = models.CharField(_('File Title'), max_length=64, null=True, blank=True)
    file = models.FileField(_('File'), upload_to='files/')
    random_key = models.CharField(_('Random Key'), max_length=16, blank=True, null=True)

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')

    def __str__(self):
        return self.title or 'Null'


class Image(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True,
                              related_name='image', verbose_name=_('Topic'))
    title = models.CharField(_('Image Title'), max_length=64, null=True, blank=True)
    image = models.ImageField(_('Image'), upload_to='images/')
    random_key = models.CharField(_('Random Key'), max_length=16, blank=True, null=True)

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')

    def __str__(self):
        return self.title or 'Null'


class TopicVote(AbstractVote):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,
                              related_name='vote', verbose_name=_('Topic'))

    class Meta:
        verbose_name = _('Topic Vote')
        verbose_name_plural = _('Topic Votes')
        unique_together = [['topic', 'user']]

    def __str__(self):
        return f'{self.topic} - {self.user}'


class CommentVote(AbstractVote):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE,
                                related_name='vote', verbose_name=_('Comment'))

    class Meta:
        verbose_name = _('Comment Vote')
        verbose_name_plural = _('Comment Votes')
        unique_together = [['comment', 'user']]

    def __str__(self):
        return f'{self.comment} - {self.user}'

templates/vote/partial/comment_form.html
{% load i18n %}

<form method="post" action="{% url 'vote:comment' %}">
  {% csrf_token %}
  <input type="hidden" id="id_topic" name="topic" value="{{ topic.pk }}">
  <input type="hidden" id="id_user" name="user" value="{{ request.user.pk }}">
  <input type="hidden" id="id_parent" name="parent" value="">
  <div class="form-group">
    <label for="id_body">{% trans 'Your Comment' %}</label>
    <textarea class="form-control" id="id_body" name="body" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary mb-2">{% trans 'Send' %}</button>
</form>

templates/vote/partial/formset.html
{% load i18n %}

<fieldset class="col-md-6">
  <legend>{% trans legend %}</legend>
  {{ formset.management_form }}
  {{ formset.non_form_errors }}
  {% for form in formset %}
    {{ form.id }}
    <div class="inline row pb-2 {{ formset.prefix }}">
      <div class="col-md-12">
        {% for field in form %}
          {% if field.name == 'file' or field.name == 'image' %}
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="{{ field.id_for_label }}" name="{{ field.html_name }}">
              <label class="custom-file-label" for="{{ field.id_for_label }}">{% if field.value %}{{ field.value }}{% else %}Choose file{% endif %}</label>
            </div>
          {% elif field.name == 'title' %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
              <input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" placeholder="{% trans 'Title' %}" value="{{ field.value }}">
            </div>
            {{ field.errors }}
          {% endif %}
        {% endfor %}
      </div>
    </div>
  {% endfor %}
</fieldset>

templates/vote/partial/topic_loop.html
{% load i18n %}

<div class="media text-muted pt-3">
  {% include 'vote/partial/vote_button.html' %}
  <div class="col-sm-12">
    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
    <a class="topic_list_group" href="{{ topic.group.get_absolute_url }}">
      {{ topic.group.title }}
    </a>
    <strong class="d-block text-gray-dark">
      <a href="{{ topic.get_absolute_url }}">
        {{ topic.title }}
      </a>
    </strong>
    {{ topic.desc }}
    </p>
    <small>
      {{ topic.date|date }} <b>-</b> <a href="{{ topic.get_absolute_url }}#comments">
        {{ topic.comment.count }} {% blocktrans count count=topic.comments.count %}{{ count }} Comment{% plural %}{{ count }} Comments{% endblocktrans %}
      </a>
    </small>
  </div>
</div>

templates/vote/partial/vote_button.html
{% load vote_tags %}

<div>
  {% get_season_active as season_active %}
  {% if season_active %}
  <a href="{% url 'vote:topic_vote' topic.slug %}?redirect={{ request.path }}" class="" role="button" aria-pressed="true">
  {% else %}
  <a href="#" class="" role="button" aria-pressed="true">
  {% endif %}
    <h3>
      <i class="fa fa-thumbs-o-up{% for vote in topic.vote.all %}{% if vote.user == request.user %} fa-thumbs-up{% endif %}{% endfor %}" aria-hidden="true"></i>
    </h3>
  </a>
  <h5 class="text-center">{{ topic.vote_count }}</h5>
</div>